import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Navbar from '../components/Navbar/Navbar'
import { DivBannerStyled } from './home.styles'
import MainCard from '../components/Card/Card'
import {Grid, Container } from '@mui/material';
import {USER_LIST} from "../mocks/auth/userList.mock";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Navbar />
        <DivBannerStyled>
        </DivBannerStyled>

        <Container>
        <Grid container spacing={2}>
         { [1,2,3].map((item) =>(
           <Grid item xs={4}>
              <MainCard data={USER_LIST}/>
           </Grid>
          ))}
        </Grid>
        </Container>
     
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Demo app
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
